const strings = {
  stringsPt: {
    foundMovie: "Encontrei isto para o filme",
    bro: " meu brou",
    searchGoogle: "Encontrei estes resultados para a pesquisa ",
    searchYoutube: "Encontrei isto no YouTube para a pesquisa ",
    temperatureHot: "Está calor, mantém-te hidratado e usa protetor solar",
    temperatureMild: "És capaz de precisar de um casaquinho mais logo",
    temperatureCold: "VAIS CONGELAAAAAAAAAAR",
    temperatureNormal: "Que temperatura agradável, aproveita o teu dia",
    alcohol: "Se fores conduzir tem cuidado que estes são fortes",
    cocktails_suggestion: "Eis as minhas sugestões de cócketeiles",
    commands: "Eis a lista de comandos disponíveis",
    explain_movies: "Clica no botão para falar e pede-me detalhes do filme que quiseres!",
    explain_cocktails: "Clica no botão para falar e pede-me uma seleção de cócketeiles para hoje à noite!",
    explain_weather: "Clica no botão para falar e pede-me detalhes do tempo para hoje!",
    explain_google: "Clica no botão para falar e pede-me para pesquisar no Google o que quiseres!",
    explain_youtube: "Clica no botão para falar e pede-me para pesquisar no YouTube o que quiseres!",
    explain_more: "Clica no botão para falar e pede-me a lista de comandos!",
    movies: "Filmes",
    cocktails: "Cocktails",
    weather: "Meteriologia",
    google: "Pesquisa Google",
    youtube: "Pesquisa Youtube",
    commands_list_movie: "&quot;Mostra-me o filme The Lord of the Rings&quot;",
    commands_list_cocktails: "&quot;Dá-me sugestões de cocktails para hoje à noite!&quot;",
    commands_list_weather: "&quot;Como vai estar o tempo?&quot;",
    commands_list_google: "&quot;Pesquisa no Google: cães fofos&quot;",
    commands_list_youtube: "&quot;Pesquisa no YouTube: Baby Shark&quot;",
  },
  stringsEn: {
    foundMovie: "Encontrei isto para o filme",
    bro: " meu brou",
    searchGoogle: "Encontrei estes resultados para a pesquisa ",
    searchYoutube: "Encontrei isto no YouTube para a pesquisa ",
    temperatureHot: "Está calor, mantém-te hidratado e usa protetor solar",
    temperatureMild: "És capaz de precisar de um casaquinho mais logo",
    temperatureCold: "VAIS CONGELAAAAAAAAAAR",
    temperatureNormal: "Que temperatura agradável, aproveita o teu dia",
    alcohol: "Se fores conduzir tem cuidado que estes são fortes",
    cocktails: "Eis as minhas sugestões de cócketeiles",
    explain_movies: "Click the talk button and ask me for details about the movie you want!",
    explain_cocktails: "Clica no botão para falar e pede-me uma seleção de cócketeiles para hoje à noite!",
    explain_weather: "Clica no botão para falar e pede-me detalhes do tempo para hoje!",
    explain_google: "Clica no botão para falar e pede-me para pesquisar no Google o que quiseres!",
    explain_youtube: "Clica no botão para falar e pede-me para pesquisar no YouTube o que quiseres!",
    explain_more: "Clica no botão para falar e pede-me a lista de comandos!"
  }
}

export default strings;