const strings = {
  stringsPt: {
    foundMovie: "Encontrei isto para o filme",
    bro: " meu brou",
    searchGoogle: "Encontrei estes resultados para a pesquisa ",
    searchYoutube: "Encontrei isto no YouTube para a pesquisa ",
    temperatureHot: "Está calor, mantém-te hidratado e usa protetor solar",
    temperatureMild: "És capaz de precisar de um casaquinho mais logo",
    temperatureCold: "VAIS CONGELAAAAAAAAAAR",
    temperatureNormal: "Que temperatura agradável, aproveita o teu dia",
    alcohol: "Se fores conduzir tem cuidado que estes são fortes",
    cocktails_suggestion: "Eis as minhas sugestões de cócketeiles",
    commands: "Eis a lista de comandos disponíveis",
    explain_movies: "Clica no botão para falar e pede-me detalhes do filme que quiseres!",
    explain_cocktails: "Clica no botão para falar e pede-me uma seleção de cócketeiles para hoje à noite!",
    explain_weather: "Clica no botão para falar e pede-me detalhes do tempo para hoje!",
    explain_google: "Clica no botão para falar e pede-me para pesquisar no Google o que quiseres!",
    explain_youtube: "Clica no botão para falar e pede-me para pesquisar no YouTube o que quiseres!",
    explain_more: "Clica no botão para falar e pede-me a lista de comandos!",
    movies: "Filmes",
    cocktails: "Cocktails",
    weather: "Meteriologia",
    google: "Pesquisa Google",
    youtube: "Pesquisa Youtube",
    home: "Home",
    cat: "Gato Random",
    random_joke: "Piada Random",
    commands_list_movie: "&quot;Mostra-me o filme The Lord of the Rings&quot;",
    commands_list_cocktails: "&quot;Dá-me sugestões de cocktails para hoje à noite!&quot;",
    commands_list_weather: "&quot;Como vai estar o tempo?&quot;",
    commands_list_google: "&quot;Pesquisa no Google: cães fofos&quot;",
    commands_list_youtube: "&quot;Pesquisa no YouTube: Baby Shark&quot;",
    commands_list_home: "&quot;Volta para a home!&quot;",
    commands_list_cat: "&quot;Mostra-me um gato qualquer&quot;",
    commands_list_meme: "&quot;Conta-me uma piada&quot;",
    ouch: "QUE CÓCEGAS",
    felizberta_speak: "Olá, o meu nome é Felizbérta. Estou aqui para te ajudar no que precisáres!",
    felizberta_ask_to_repeat: "Não percebi, podes repetir por favor?",
    api_error: "Houve um erro a ir buscar os seus resultados, por favor tente mais tarde",
    random_cat: "Aqui tens um gato fofo, miau"
  },
  stringsEn: {
    foundMovie: "I found these result for the movie ",
    bro: " bro",
    searchGoogle: "I found these results for the Google search: ",
    searchYoutube: "I found these result for the YouTube search: ",
    temperatureHot: "It's very hot, stay hydrated and use your sunscreen!",
    temperatureMild: "You might need a light jacket later on",
    temperatureCold: "YOU'RE GONNA FREEZE",
    temperatureNormal: "What a lovely temperature, enjoy your day!",
    alcohol: "If you're going to drive, be careful. These are quite strong",
    cocktails: "Here are my cocktail suggestions!",
    explain_movies: "Click the talk button and ask me for details about the movie you want!",
    explain_cocktails: "Click the talk button and ask me for a selection of cocktails for tonight!",
    explain_weather: "Click the talk button and ask me for the weather status!",
    explain_google: "Click the talk button and ask me to search Google for whatever you want!",
    explain_youtube: "Click the talk button and ask me to search YouTube for whatever you want!",
    explain_more: "Click the talk button and ask me for my available commands!",
    movies: "Movies",
    cocktails: "Cocktails",
    weather: "Weather",
    google: "Google search",
    youtube: "YouTube search",
    home: "Home",
    cat: "Random Cat",
    random_joke: "Random Joke",
    commands_list_movie: "&quot;Show me the movie The Lord of the Rings&quot;",
    commands_list_cocktails: "&quot;Give me cocktail suggestion for tonight!&quot;",
    commands_list_weather: "&quot;How's the weather?&quot;",
    commands_list_google: "&quot;Search Google: cute dogs&quot;",
    commands_list_youtube: "&quot;Search YouTube: Baby Shark&quot;",
    commands_list_home: "&quot;Go back home!&quot;",
    commands_list_cat: "&quot;Show me a random cat&quot;",
    commands_list_meme: "&quot;Tell me a joke&quot;",
    ouch: "Ouch",
    felizberta_speak: "Olá, o meu nome é Felizbérta. Estou aqui para te ajudar no que precisáres!",
    felizberta_ask_to_repeat: "Can you please repeat that?",
    api_error: "There was an error fetching your results, please try again later",
    random_cat: "Here's a cute cat, awwww"
  }
}

export default strings;