const strings = {
  stringsPt: {
    app_desc: `A pesquisa por voz confere a esta aplicação uma utilização intuitiva através de comandos que permitem
        uma maior velocidade no acesso à informação desejada. Este espaço em constante atualização promete mantê-lo 
        entretido enquanto pesquisa as suas mais peculiares curiosidades. Quer pretenda saber detalhes sobre o seu 
        filme favorito, pedir sugestões de cocktails num dia menos inspirado, saber imeditamente a meteoreologia para 
        a sua exata localização, fazer uma pesquisa no Google ou no Youtube, ou até escapar de um momento mais monótono 
        com um Gif divertido, poderá fazê-lo clicando no botão de activação de voz que se encontra no fundo desta página.`,
    home_page_subtitle: "A nova App de voz!",
    foundMovie: "Encontrei isto para o filme ",
    no_movie_found: "Não encontrei resultados para o filme ",
    bro: " meu brou",
    searchGoogle: "Encontrei estes resultados para a pesquisa ",
    searchYoutube: "Encontrei isto no YouTube para a pesquisa ",
    temperatureHot: "Está calor, mantém-te hidratado e usa protetor solar",
    temperatureMild: "És capaz de precisar de um casaquinho mais logo",
    temperatureCold: "VAIS CONGELAAAAAAAAAAR",
    temperatureNormal: "Que temperatura agradável, aproveita o teu dia",
    alcohol: "Se fores conduzir tem cuidado que estes são fortes",
    cocktails_suggestion: "Eis as minhas sugestões de cócketeiles",
    joke: "Tenta não chorar a rir das minhas piada hilárias mano",
    commands: "Eis a lista de comandos disponíveis",
    explain_movies: "Clica no botão para falar e pede-me detalhes do filme que quiseres!",
    explain_cocktails: "Clica no botão para falar e pede-me uma seleção de cócketeiles para hoje à noite!",
    explain_weather: "Clica no botão para falar e pede-me detalhes do tempo para hoje!",
    explain_google: "Clica no botão para falar e pede-me para pesquisar no Google o que quiseres!",
    explain_youtube: "Clica no botão para falar e pede-me para pesquisar no YouTube o que quiseres!",
    explain_more: "Clica no botão para falar e pede-me a lista de comandos!",
    movies: "Filmes",
    cocktails: "Cocktails",
    weather: "Meteriologia",
    google: "Pesquisa Google",
    youtube: "Pesquisa Youtube",
    home: "Home",
    cat: "Gato Random",
    random_joke: "Piada Random",
    commands_list_movie: "&quot;Mostra-me o filme The Lord of the Rings&quot;",
    commands_list_cocktails: "&quot;Dá-me sugestões de cocktails para hoje à noite!&quot;",
    commands_list_weather: "&quot;Como vai estar o tempo?&quot;",
    commands_list_google: "&quot;Pesquisa no Google: cães fofos&quot;",
    commands_list_youtube: "&quot;Pesquisa no YouTube: Baby Shark&quot;",
    commands_list_home: "&quot;Volta para a home!&quot;",
    commands_list_cat: "&quot;Mostra-me um gato qualquer&quot;",
    commands_list_meme: "&quot;Conta-me uma piada&quot;",
    ouch: "QUE CÓCEGAS",
    felizberta_speak: "Olá, o meu nome é Felizbérta. Estou aqui para te ajudar no que precisáres!",
    felizberta_ask_to_repeat: "Não percebi, podes repetir por favor?",
    api_error: "Houve um erro a ir buscar os seus resultados, por favor tente mais tarde",
    random_cat: "Aqui tens um gato fofo, miau"
  },
  stringsEn: {
    app_desc: `Voice-activated search enables this app to have a very intuitive navigation with time-saving commands 
    that give access to the desired information. This space, in constant update, promisses to keep you entertained while
    you browse through your most peculiar curiosities. Whether you want to know the details of your favourite movies,
    ask for suggestions of cocktails on a less inspired day, to immediately know the weather for your exact location, to
    browse through Google and Youtube, or even to escape a monotonous moment with a funny Gif, you'll be able to do that
    by clicking on the activation button that you'll find on the bottom of this page.`,
    home_page_subtitle: "The new voice App!",
    foundMovie: "I found these result for the movie ",
    no_movie_found: "No results found for the movie ",
    bro: " bro",
    searchGoogle: "I found these results for the Google search: ",
    searchYoutube: "I found these result for the YouTube search: ",
    temperatureHot: "It's very hot, stay hydrated and use your sunscreen!",
    temperatureMild: "You might need a light jacket later on",
    temperatureCold: "YOU'RE GONNA FREEZE",
    temperatureNormal: "What a lovely temperature, enjoy your day!",
    alcohol: "If you're going to drive, be careful. These are quite strong",
    joke: "Try not to die laughing at my super funny jokes yo",
    cocktails_suggestion: "Here are my cocktail suggestions!",
    explain_movies: "Click the talk button and ask me for details about the movie you want!",
    explain_cocktails: "Click the talk button and ask me for a selection of cocktails for tonight!",
    explain_weather: "Click the talk button and ask me for the weather status!",
    explain_google: "Click the talk button and ask me to search Google for whatever you want!",
    explain_youtube: "Click the talk button and ask me to search YouTube for whatever you want!",
    explain_more: "Click the talk button and ask me for my available commands!",
    movies: "Movies",
    cocktails: "Cocktails",
    weather: "Weather",
    google: "Google search",
    youtube: "YouTube search",
    home: "Home",
    cat: "Random Cat",
    random_joke: "Random Joke",
    commands_list_movie: "&quot;Show me the movie The Lord of the Rings&quot;",
    commands_list_cocktails: "&quot;Give me cocktail suggestion for tonight!&quot;",
    commands_list_weather: "&quot;How's the weather?&quot;",
    commands_list_google: "&quot;Search Google: cute dogs&quot;",
    commands_list_youtube: "&quot;Search YouTube: Baby Shark&quot;",
    commands_list_home: "&quot;Go back home!&quot;",
    commands_list_cat: "&quot;Show me a random cat&quot;",
    commands_list_meme: "&quot;Tell me a joke&quot;",
    ouch: "Ouch",
    felizberta_speak: "Hello, my name is Felizberta. I'm here to help you however you need!",
    felizberta_ask_to_repeat: "Can you please repeat that?",
    api_error: "There was an error fetching your results, please try again later",
    random_cat: "Here's a cute cat, meow"
  }
}

export default strings;